//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NaruciISjedi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Reports = new HashSet<Report>();
        }
    
        public int narudzbaID { get; set; }
        public Nullable<int> IDKorisnik { get; set; }
        public Nullable<int> kolicina { get; set; }
        public Nullable<int> IDProizovd { get; set; }
        public Nullable<System.DateTime> vrijemeDostave { get; set; }
        public Nullable<double> ukupnaCijena { get; set; }
        public string adresaDostave { get; set; }
        public string kontakt { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Report> Reports { get; set; }
    }
}
